chore: Populate user-agent while using CPR local model to upload models.
googleapis/python-aiplatform pull request #1191
Opened 2022-05-02 16:14 UTC by abcdefgs0324

2022-05-16 16:15 UTC, kthytang requested changes

2022-05-16 22:49 UTC, abcdefgs0324 commented on google/cloud/aiplatform/initializer.py
> +            user_agent = f"{user_agent};{';'.join(appended_user_agent)}"
Done, thanks!

2022-05-19 06:52 UTC, kthytang approved these changes

2022-05-19 06:52 UTC, kthytang commented on google/cloud/aiplatform/base.py
> +                it will be separated by semicolons.
semicolons -> space

2022-05-19 06:52 UTC, kthytang commented on google/cloud/aiplatform/initializer.py
> +                separated by semicolons.
Same here

2022-05-19 22:03 UTC, merged