chore: Add code owners for Vertex Metadata SDK
googleapis/python-aiplatform pull request #1515
Opened 2022-07-18 21:30 UTC by SinaChavoshi

Adding the code owner group for Vertex AI Metadata SDK team.

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [ ] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/python-aiplatform/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [X] Ensure the tests and linter pass
- [X] Code coverage does not decrease (if any source code was changed)
- [X] Appropriate docs were updated (if necessary)

Fixes #<issue_number_goes_here> 🦕

2022-07-18 21:31 UTC, jialuzh approved these changes

2022-07-20 11:25 UTC, parthea approved these changes

2022-07-20 11:28 UTC, parthea requested changes

2022-07-20 11:28 UTC, parthea commented on .github/CODEOWNERS
> +/tests/unit/aiplatform/**              @googleapis/vertex-ai-metadata
Please revert these 2 lines as they already exist above
```suggestion
```

2022-07-20 16:16 UTC, SinaChavoshi commented on .github/CODEOWNERS
> +/tests/unit/aiplatform/**              @googleapis/vertex-ai-metadata
done.

2022-07-20 18:30 UTC, parthea approved these changes

2022-07-20 19:57 UTC, merged