chore: add model monitoring SDK code samples to model-builder
googleapis/python-aiplatform pull request #1574
Opened 2022-08-05 23:04 UTC by rosiezou

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [ ] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/python-aiplatform/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #<issue_number_goes_here> 🦕

2022-08-10 23:54 UTC, yil532 approved these changes
LGTM

2022-08-11 02:58 UTC, yil532 approved these changes
LGTM

2022-08-12 15:53 UTC, dizcology requested changes

2022-08-12 15:53 UTC, dizcology commented on samples/model-builder/create_model_monitoring_job_example.py
> +def create_model_monitoring_job_example(
Why are we exposing all these arguments in the sample function?  The sample function’s body should illustrate a use case of a library method, and the sample function and its arguments are there for sample testing purposes, and we are not expecting the user to run the sample function.

We expect the illustrated library method to have sensible defaults for most of its arguments.  As such the sample function should expose only what is needed at sample testing time. As is right now the sample function appears to be doing nothing but flattening some of the parameters.

2022-08-12 16:14 UTC, dizcology commented on samples/model-builder/create_model_monitoring_job_example.py
> +def create_model_monitoring_job_example(
Here is an example where the sample function exposes only what’s needed for sample testing and the sample function body illustrates a use case: https://github.com/googleapis/python-aiplatform/blob/main/samples/snippets/job_service/create_custom_job_sample.py

2022-09-30 20:59 UTC, rosiezou commented
closing this for now. will revisit at a later time.

2022-09-30 20:59 UTC, closed without merging