feat: Add extra_environment_variables parameter to LocalModel.build_cpr_model() method
googleapis/python-aiplatform pull request #1832
Opened 2022-12-07 09:13 UTC by MichaelisTrofficus

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [ ] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/python-aiplatform/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)
- [ ] Get the necessary approvals
- [ ] Once the last commit on the PR has been approved, add the "ready to pull" label to the Pull Request

Note: do not merge your PR from GitHub. Adding the "ready to pull" label is the final step in the review process.
After approvals, the changes in your PR will be committed to the `main` branch and this PR will be closed.

Fixes #<issue_number_goes_here> 🦕

2023-01-04 02:10 UTC, rosiezou requested changes
@MichaelisTrofficus please add appropriate unit and system test coverage for this PR.

2023-01-07 10:09 UTC, MichaelisTrofficus commented
Hi @rosiezou , I cannot trigger the Presubmit - Unit Tests action even if I close and reopen again the PR. Do you know what might be happening?

2023-01-17 17:04 UTC, MichaelisTrofficus commented
Hi @rosiezou , should I delete the PR and try it again?

2023-01-31 21:28 UTC, rosiezou commented
@MichaelisTrofficus please fix failed unit tests and add coverage for the additional optional args.

2023-05-10 19:16 UTC, kthytang commented
PR looks good to me. Thanks.

2025-06-25 18:17 UTC, matthew29tang commented
Closing due to inactivity.

2025-06-25 18:17 UTC, closed without merging