fix: rename schema.training_job.definition tabular_task to automl_tabular
googleapis/python-aiplatform pull request #218
Opened 2021-02-10 19:59 UTC by morgandu

Fixes https://b.corp.google.com/issues/179922436

2021-02-11 01:36 UTC, vinnysenthil approved these changes

2021-02-12 16:07 UTC, sasha-gitg requested changes

2021-02-12 16:07 UTC, sasha-gitg commented on google/cloud/aiplatform/schema.py
>          automl_image_classification_task = "gs://google-cloud-aiplatform/schema/trainingjob/definition/automl_image_classification_1.0.0.yaml"
The AutoML Image definition names should also be changed.

2021-02-16 16:45 UTC, sasha-gitg approved these changes
LGTM

2021-02-16 17:24 UTC, merged