feat: MBSDK Tabular samples
googleapis/python-aiplatform pull request #338
Opened 2021-04-19 18:00 UTC by aribray

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:

Tracking Bug: [MB SDK Samples - Milestone 1](https://buganizer.corp.google.com/issues/180729765)
- [ ] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/python-aiplatform/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #<issue_number_goes_here> 🦕

2021-04-21 16:31 UTC, sasha-gitg requested changes

2021-04-21 16:31 UTC, sasha-gitg commented on samples/model-builder/create_training_pipeline_tabular_classification_sample.py
> +    optimization_prediction_type: str = 'classification',
Since this is a classification sample, I think this can be fixed in the call.

2021-04-21 16:31 UTC, sasha-gitg commented on samples/model-builder/create_training_pipeline_tabular_regression_sample.py
> +    optimization_prediction_type: str = 'regression',
Same comment for fixing this argument.

2021-04-21 23:04 UTC, sasha-gitg approved these changes

2021-04-23 17:39 UTC, dizcology approved these changes

2021-04-30 06:12 UTC, vinnysenthil approved these changes

2021-04-30 06:12 UTC, vinnysenthil commented
@googlebot I consent.

2021-04-30 18:04 UTC, merged