Fixed missing job credentials on PipelineJobSchedule init
googleapis/python-aiplatform pull request #4040
Opened 2024-07-03 12:34 UTC by AlexejPenner

This addresses the following [Issue](https://github.com/googleapis/python-aiplatform/issues/4039). When creating a PipelineJob object, I would expect and Schedules created from this job to inherit credentials, location and project from the job.

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [x] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/python-aiplatform/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)
- [ ] Get the necessary approvals
- [ ] Once the last commit on the PR has been approved, add the "ready to pull" label to the Pull Request

Note: do not merge your PR from GitHub. Adding the "ready to pull" label is the final step in the review process.
After approvals, the changes in your PR will be committed to the `main` branch and this PR will be closed.

Fixes #4039 🦕

2024-07-03 12:49 UTC, eliottiti approved these changes

2024-07-03 22:24 UTC, jaycee-li approved these changes
Thanks @AlexejPenner for the fix!

2024-07-04 17:18 UTC, jaycee-li requested changes

2024-07-04 17:18 UTC, jaycee-li commented on google/cloud/aiplatform/pipeline_jobs.py
> +            project=self.project
`project=self.project,`

2024-07-04 17:29 UTC, strickvl commented on google/cloud/aiplatform/pipeline_jobs.py
> +            project=self.project
```suggestion
            project=self.project,
```

2024-07-05 16:23 UTC, jaycee-li approved these changes

2024-07-09 20:28 UTC, jaycee-li commented
Hi @strickvl , could you please sign the CLA so that we can merge this PR.

https://github.com/googleapis/python-aiplatform/pull/4040/checks?check_run_id=27174525571

2024-07-26 14:40 UTC, closed without merging