feat: add tensorboard resource management
googleapis/python-aiplatform pull request #539
Opened 2021-07-13 18:23 UTC by morgandu

- [x] add Tensorboard class for resource management 
- [x] Ensure the tests and linter pass

Fixes #<b/190835588> 🦕

2021-07-14 18:09 UTC, sasha-gitg requested changes

2021-07-15 23:31 UTC, morgandu commented on google/cloud/aiplatform/compat/types/__init__.py
> -    tensorboard_service as tensorboard_service_v1beta1,
There were two entries of tensorboard_service_v1beta1, this is was one of duplicated line item

2021-07-16 19:28 UTC, sasha-gitg approved these changes
LGTM. Thanks, Morgan!

2021-07-16 19:28 UTC, sasha-gitg commented on google/cloud/aiplatform/tensorboard/tensorboard.py
> +                Optional description of this Tensorboard.
Format should be `Optional. Description of this Tensorboard`. Please apply throughout this PR.

2021-07-20 20:50 UTC, vinnysenthil approved these changes

2021-07-21 00:29 UTC, merged