Update constants.py
googleapis/python-aiplatform pull request #811
Opened 2021-11-01 17:09 UTC by wanyixu199

Add new regions of Vertex Tables in the SUPPORTED_REGIONS set so users can use the SDK in these 3 new regions.
While the implementation of these new regions is complete the change is required for the E2E tests of these regions.

2021-11-01 17:22 UTC, wanyixu199 commented
@googlebot I signed it!

2021-11-01 17:27 UTC, wanyixu199 commented
@googlebot I signed it!

2021-11-05 20:11 UTC, sasha-gitg requested changes
Please add `us-west2`

2021-11-08 13:35 UTC, sasha-gitg approved these changes

2021-11-08 19:24 UTC, merged