Support nested resources
googleapis/python-aiplatform pull request #901
Opened 2021-12-09 16:01 UTC by sasha-gitg

2021-12-10 20:25 UTC, morgandu requested changes

2021-12-13 19:10 UTC, sasha-gitg commented on google/cloud/aiplatform/tensorboard/tensorboard_resource.py
> +    client_class = utils.TensorboardClientWithOverride
Yes, we will have different subclass for TB Experiment, Run, and Timeseries.

2021-12-13 19:13 UTC, sasha-gitg commented on google/cloud/aiplatform/initializer.py
> +        tensorboard_resource: Optional[str] = None,
Thanks for catching this. Removed this argument. I will add it back in when supported.

2021-12-13 19:16 UTC, sasha-gitg commented on google/cloud/aiplatform/utils/__init__.py
> +        convert_camel_case_resource_noun_to_snake_case(resource_noun): resource_name,
Updated the docstring.

2021-12-14 00:39 UTC, morgandu approved these changes

2021-12-16 16:16 UTC, merged