Added `model.update`  method
googleapis/python-aiplatform pull request #952
Opened 2022-01-11 20:50 UTC by ivanmkc

Added ability to update `display_name`, `description` and `labels`.

Fixes https://b.corp.google.com/issues/213921337

2022-01-11 20:53 UTC, sasha-gitg commented on google/cloud/aiplatform/models.py
> +        cls,
This should be an instance method and should update the instance.

2022-01-19 19:03 UTC, sasha-gitg requested changes
Please add or update an integration test to use this method:

An additional test case can be added here using the same model: https://github.com/googleapis/python-aiplatform/blob/main/tests/system/aiplatform/test_model_upload.py

It can also be added to this e2e test: https://github.com/googleapis/python-aiplatform/blob/main/tests/system/aiplatform/test_e2e_tabular.py

2022-01-21 22:34 UTC, ivanmkc commented on google/cloud/aiplatform/models.py
> +        return self
Done

2022-01-21 22:34 UTC, ivanmkc commented on google/cloud/aiplatform/models.py
> +        current_model_proto = self.gca_resource
Done.

2022-01-21 22:35 UTC, ivanmkc commented on google/cloud/aiplatform/models.py
> +    ):
Done.

2022-01-24 16:45 UTC, sasha-gitg approved these changes
LGTM!

2022-01-24 16:45 UTC, sasha-gitg commented on google/cloud/aiplatform/models.py
> +        _ = self.api_client.update_model(
```suggestion
        self.api_client.update_model(
```

2022-01-24 19:22 UTC, merged